// react-todo/src/Books/AddBook.js
import React, { useState } from "react";

export function AddBook({add}) {
  const [book, setBook] = useState({
    title: "",
    author: "",
    pagesCount: 0,
    publishDate: "",
  });

  function onSubmit(e) {
    e.preventDefault();

    add(book);
  }

  function onChange(e) {
    const fieldName = e.target.name;
    const newValue = e.target.value;
    setBook((prevBook) => ({...prevBook, [fieldName]: newValue}));
  }

  return (
    <form onSubmit={onSubmit}>
      <h3>Add</h3>
      <input name="title" value={book.title} onChange={onChange}/>
      <input name="author" value={book.author} onChange={onChange}/>
      <input
        name="pagesCount"
        type="number"
        value={book.pagesCount}
        onChange={onChange}
      />
      <input
        name="publishDate"
        type="date"
        value={book.publishDate}
        onChange={onChange}
      />

      <button type="submit">Add</button>
    </form>
  );
}

// sample-ng-client/src/app/components/add-book/add-book.component.ts
import {Component, Input, OnInit} from '@angular/core';
import {BookModel, BooksRequestService} from '../../services/books-request.service';
import {NgForm} from '@angular/forms';

@Component({
  selector: 'app-add-book',
  templateUrl: './add-book.component.html',
  styleUrls: ['./add-book.component.scss']
})
export class AddBookComponent implements OnInit {

  book: BookModel = {
    title: '',
    author: '',
    pagesCount: 0,
    publishDate: null
  };

  @Input()
  addBook: (BookModel) => void;

  constructor(private readonly service: BooksRequestService) { }

  ngOnInit(): void {
  }

  submit(form: NgForm): void {
    this.addBook(form.value as BookModel);
  }
}

<form #form="ngForm" (ngSubmit)="submit(form)">
  <h3>Add</h3>
  <input [(ngModel)]="book.title" name="title" />
  <input [(ngModel)]="book.author" name="author" />
  <input type="number" [(ngModel)]="book.pagesCount" name="pagesCount" />
  <input type="date" [(ngModel)]="book.publishDate" name="publishDate" />

  <button type="submit">Add</button>
</form>
